### ISSUE TITLE
Completion for "stg add" on rust branch does not complete filenames

### ISSUE THREAD

**Issue by larsks** [stacked-git/stgit#191]
I've been playing around with the `rust` branch, which seems to work great so far, but I've noticed that the completion installed by `stg completion bash` does not allow the `stg add` command to complete filenames. For now I'm just retraining myself to use `git add` instead, but I wasn't sure if this was intentional or not.

**Comment by jpgrayson** [comment]
I appreciate this report, thank you. I'd really like StGit's shell completions to be top-notch, so this is good feedback.

The completions generated by the Python implementation of StGit were setup to fallback to bash's default filename completion whenever a more specific completion wasn't available. For the new Rust implementation, I changed it to do no completion for things that we don't explicitly complete. This includes aliases.

Two options for this case:

1. Change it so that aliases fall-back to bash's default filename completion. I suspect this would be straightforward.
2. Figure out how to punt to git's completion when expanding a StGit shell alias (such as `!git add`) such that the full completion capability is available. Non-obvious how to do this.

I'll note that doing (2) for zsh and fish completions is pretty normal/straightforward and thus is already supported in those StGit completion scripts. Bash is pretty primitive in comparison.

**Comment by larsks** [comment]
> I changed it to do no completion for things that we don't explicitly complete. This includes aliases.

Absent a better solution, would it make sense to fall back to the "use filename completion" model for bash completions? My fingers are used to using `stg add/mv/rm` when working with stg-enabled branches, and the lack of filename completion is frustrating.

If you don't like this as default behavior, what about allowing it to be enabled conditionally (`stg completion bash --default-filename-completion`)?

**Comment by jpgrayson** [comment]
I think falling back to file name completion for aliases specifically makes sense. In a variety of other StGit completion contexts, where we know that file name completion is not appropriate, my sense is that it is better to not complete at all instead of completing file names.

Note that the completion for ‘git add’ is more sophisticated than bash’s default file name completion. It offers completions for the subset of addable files, as opposed to all files. This is where it would be great to be able to punt to the full-featured completion for StGit aliases’ expansions like we do for zsh and fish. I don’t know how to do this for bash though.

**Comment by jpgrayson** [comment]
Modified bash completions in [62d6c98](https://github.com/stacked-git/stgit/commit/62d6c98f3216d5d5ee64ff7be923c99644d0c473) to do filename completion for shell aliases. This resolves the specific issue with `stg add` while still avoiding using filename completions in other contexts where filenames definitely should not be completed.
