### ISSUE TITLE
stg push (Rust version) fails

### ISSUE THREAD

**Issue by ctmarinas** [stacked-git/stgit#192]
For some reason, if I do this (on a Linux kernel repository):
```
$ stg new test1
$ vi Makefile --> some editing
$ stg refresh
$ stg new test2
$ vi Makefile --> some more editing, potentially on the same line
$ stg refresh
$ stg pop -n2
$ stg push test2
error: git diff-tree:
```
The changes don't need to conflict. I think if it requires a three-way merge it fails to push but doesn't say anything more about how `git diff-tree` failed.

Additional info:
```
$ stg --version
Stacked Git 2.0.0-alpha.1
Copyright (C) 2005-2022 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.30.2
```

**Comment by jpgrayson** [comment]
The root of this problem is that StGit is using the `--allow-empty` option to `git apply`, which was introduced in git 2.35 (Jan 2022) and thus fails for all git versions <2.35.0.

Using `git apply --allow-empty` is nice because it allows us to take diffs from external origins (i.e. for `import`, `fold`, etc.) and simply apply them. Without `--allow-empty`, we have to use other means to figure out whether a diff is empty. The trivial approach is the only one currently in our quiver: test whether the diff stream is empty of bytes. The problem with this approach is that a diff stream may reasonably have header/context without any diff hunks. Such a diff stream counts as "empty" to `git apply`, but has non-zero bytes and thus escapes the trivial emptiness test. Determining whether some non-empty stream of bytes contains valid diff hunks requires a full-fledged diff parser, which is why it is really nice to let `git apply` do that job.

BUT, I don't think it's reasonable for StGit to drop support for git versions that are less than a year old, so the plan is to stop using `git apply --allow-empty`.

I need to audit the various code paths that end up using `git apply` and ensure that empty (no bytes) diffs are accounted for upstream of `git apply`. For cases where diffs are generated internally, we can test tree ids to determine whether a diff will be empty or not before applying it. For cases where the diff comes from an external source, empty-ish patches will behave more similarly to the Python implementation.

I have also figured out why the error is misapplied to `git diff-tree` instead of `git apply` and have a repair for that.
