### ISSUE TITLE
Signing a series of patches

### ISSUE THREAD

**Issue by jkleckner** [stacked-git/stgit#197]
Would it make sense to have a function to sign a series of patches with PGP or do most people only sign the top-most patch when preparing a merge request?

**Comment by jpgrayson** [comment]
My strategy is to set `commit.gpgSign=true` either globally or on a per-repository basis. This causes StGit patches (and thuse their underlying commits) to be signed. All of StGit's commands that create or modify patches (`new`, `refresh`, `edit`, etc.) respect the `commit.gpgSign` config option.

Note that there is also a `stgit.gpgSign` config option that determines whether StGit signs commits to its metadata branch (i.e. `refs/stacks/<branch>`. I disable this option since I don't typically share (pull, push) the stack metadata and signing commits has a performance impact.

StGit could potentially add explicit command line knob(s) for enabling GPG signatures, but I've tended toward wanting the simplicity of turning this on/off in the config and not dealing with it per-patch.

**Comment by jkleckner** [comment]
@jpgrayson  Thank you!
