### ISSUE TITLE
"failed to lock file" error

### ISSUE THREAD

**Issue by larsks** [stacked-git/stgit#205]
I accidentally aborted an `stg goto` operation (configured to gpg sign commits by default, fingers didn't anticipate the password prompt so I typed the wrong thing, causing the commit to fail, causing stg to fail), and subsequent `stg` operations failed with:

```
error: failed to lock file '/home/lars/projects/k8s-perf-tools/db-perf/.git/refs/stacks/main.lock' for writing: ; class=Os (2); code=Locked (-14)
```

Removing the lock file allowed things to continue, but this seems like a bug: stg should clean up lockfiles on exit, and even if it fails to clean up lock files, any locks it holds shouldn't persist when the process exits.

**Comment by jpgrayson** [comment]
Hmmm, this is an interesting case. Thanks for reporting it, @larsks.

There is one place in StGit's [transaction code](https://github.com/stacked-git/stgit/blob/1f8cdbfa9c35a3301b2df7c9bb0b84daff4d0747/src/stack/transaction.rs#L353-L408) where the stack reference (e.g. `refs/stacks/main` and patch references (`refs/patches/main/xxx`) are explicitly locked using a `git2::Transaction`. I think the first step would be to confirm that this is the critical section of code where the lock is created. If it is (it probably is), then we would need to figure out how to ensure the lock file(s) are cleaned up.

I'll note that it seems possible to ensure locks are cleaned up with a SIGTERM, but not with a SIGKILL and/or other arbitrary exit conditions. Also, not sure what mechanisms are available on Windows since that platform doesn't really do signals.

**Comment by larsks** [comment]
Here's a complete reproducer for this situation.

## Prerequisites

You need git configured to automatically sign commits.

- Ensure that `commit.gpgsign=true`.
- Ensure that `user.signkey` is set to something useful

You need gpg configured to prompt for a passphrase on the terminal:

- Set `pinentry-mode loopback` in `~/.gnupg/gpg.conf`
- Set `allow-loopback-pinentry` in `~/.gnupg/gpg-agent.conf`

## Initial repository state

We start with:

```
$ stg series
+ repair-reference-in-cmd-module
> add-lint-api-doc-target-to
```

## Procedure

1. Ensure that you don't have a cached passphrase (and that any
   configuration changes you made in `gpg-agent.conf` are activated):

    ```
    echo RELOADAGENT | gpg-connect-agent
    ```

1. Try to change patches using e.g. `stg pop`. Abort the operation
   with CTRL-C when prompted for a passphrase.

    ```
    $ stg pop
    - add-lint-api-doc-target-to
    > repair-reference-in-cmd-module
    Enter passphrase:
    ```

1. Try to repeat the above command:

    ```
    $ stg pop
    error: HEAD and stack top are not the same. This can happen if you modify the branch with git. See `stg repair --help` for next steps to take.
    ```

1. Attempt to repair the branch. Enter the passphrase when prompted.

    ```
    $ stg repair
    info: `add-lint-api-doc-target-to` is now unapplied
    error: failed to lock file '/home/lars/src/repro/.git/refs/stacks/master.lock' for writing: ; class=Os (2); code=Locked (-14)
    ```

**Comment by jpgrayson** [comment]
This reproducing procedure is really helpful. I am able to reproduce the problem and have started taking a look at what's going on.

**Comment by jpgrayson** [comment]
For the case where `stg pop` fails due to the gpg prompt being aborted, the transaction should now be fully rolled back such that the stack and branch state are consistent. So no more head/top mismatch state or needing to run `stg repair` afterward. Looks like you're getting that part of the new behavior. However, in my test cases, I have not seen the index be in an inconsistent state, so that's new/unexpected. I'm not immediately able to reproduce that problem either--could use some help with that.

**Comment by jpgrayson** [comment]
I am able to reproduce the above when I configure gpg with `pinentry-mode loopback`. I had been using a different pinentry program (`pinentry-qt`) where cancelling the pinentry would result in StGit resuming control after its child `git` process exited with a failure such that rollback would occur.

```
$ stg pop                                                                                                                                                                                                            master
- add-test-for-gpg-failure
> robust-stack-transaction
@ add-test-for-gpg-failure (rolled back)
error: `git commit-tree`: error: gpg failed to sign the data
Command aborted (all changes rolled back)
$ stg status
```

So there is something about hitting ctrl-c with the loopback pinentry that seems to cause the parent `stg` process to be killed hard such that it does not get a chance to perform its new-and-improved rollback.

**Comment by larsks** [comment]
> So there is something about hitting ctrl-c with the loopback
> pinentry that seems to cause the parent stg process to be killed
> hard such that it does not get a chance to perform its
> new-and-improved rollback.

The `SIGINT` here is delivered to `gpg`, and `git`, and `stg` (which
wouldn't be the case when cancelling a GUI password prompt. Does the
new transaction code get triggered when stg is interrupted by a
signal?

**Comment by jpgrayson** [comment]
The updated transaction rollback code currently assumes that the subordinate `git commit-tree` process it calls will return. I am looking into adding a `SIGINT` handler using the `ctrlc` package.
