### ISSUE TITLE
Short command forms like "stg ser" no longer work in 2.x

### ISSUE THREAD

**Issue by lorinder** [stacked-git/stgit#240]
With stg < 2.0, I could e.g. type `stg ser` instead of `stg series`, or `stg ref` instead of `stg refresh`.  I believe in the past (1.x or earlier) it would work whenever a unique prefix of a command, but am not sure about the exact rule that was used.  This useful feature seems gone;  I miss it for the long-to-type commands "series" and "refresh".

There are several possible ways something similar could be restored.  For long-to-type (> 4 letters), frequently-used commands, one might introduce explicitly-specified short aliases, or one might restore the old behavior where any unique command prefix would do.

Output of `stg --version`:
```sh
% stg --version
Stacked Git 2.0.1
Copyright (C) 2005-2022 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.38.1
```

Example command line:
```
% /usr/bin/stg ser
error: The subcommand 'ser' wasn't recognized

  Did you mean 'series'?

  If you believe you received this message in error, try re-running with 'stg -- ser'

Usage: stg [OPTIONS] <command> [...]
       stg [OPTIONS] <-h|--help>
       stg --version

For more information try '--help'
```

Desired behavior:  Instead of suggesting the `series` command, it should actually execute it.  Of course not for random typos, but according to a sensible rule.

Workaround: As a workaround, I'm wrapping `stg` by a shell script to handle the cases that matter to me:
```sh
#!/bin/sh

stg=/usr/bin/stg

cmd=$1
shift
if [ "x$cmd" == "xser" ] ; then
        exec $stg series "$@"
elif [ "x$cmd" == "xref" ] ; then
        exec $stg refresh "$@"
fi
exec $stg "$cmd" "$@"
```

**Comment by jpgrayson** [comment]
Thanks for this issue report, @lorinder.

I made a conscious choice in StGit 2.0 to no longer allow unambiguous command prefixes to work. Several reasons:

- Avoid surprising behavior when command has a real typo versus an intentional prefix.
- Avoid implicitly claiming "command namespace" with all the valid prefixes. This command namespace can otherwise be used for aliases.
- StGit 2.0 has a much improved alias system. And this alias system can be used to create aliases for common/useful prefixes.

My suggested solution is to setup a couple global aliases instead of using a wrapper script. I.e.:

```
$ git config --global stgit.alias.ser series
$ git config --global stgit.alias.ref refresh
```

An even more brief alias for `stg series` would be `stg ls`, which would be setup with
```
$ git config --global stgit.alias.ls series
```

And if, for example, you have some favorite options to `stg series`, those can be part of the alias too:

```
git config --global stgit.alias.ls 'series --description'
```

That said, I'm not categorically opposed to having some predefined prefix aliases for various commands. I'd like opinions on setting up aliases versus having baked-in prefix aliases.

**Comment by lorinder** [comment]
Thank you, @jpgrayson!  I wasn't aware of this possibility to set aliases, and that is indeed much better than my wrapper script hack.

I agree this is a better solution than the unique prefix rule in the previous `stg` versions.  Given that the user can configure this, I also don't think that baked-in aliases would necessarily be needed.

However, I think what may be missing is documentation of this feature.  I can't find it documented anywhere. In fact, I wasn't aware that stgit can be configured at all.

Thanks again for your response!  It certainly solved the problem for me.

**Comment by jpgrayson** [comment]
> I can't find it documented anywhere.

I've recently updated the `stg(1)` man page to include details about all of StGit's configuration variables, including `stgit.alias.*` (ae884eb8642ce2d7fb1b244d59d0a5fa8d430003). The improved man page will be in the next release.

There is probably also an opportunity to add something to [the tutorial](https://stacked-git.github.io/guides/tutorial/) about aliases, but I don't have an immediate plan to work on that ([patches welcome](https://github.com/stacked-git/stacked-git.github.io)).

I'm going to close this issue with the solution being to encourage use of StGit aliases.

**Comment by lws-team** [comment]
> I'd like opinions on setting up aliases versus having baked-in prefix aliases.

It would be ideal if stgit knew the old common abbreviations out of the box, and you could modify them with the alias commands.  Then nobody coming from the old, distro-provided stgit will get surprised dozens of times a day when their muscle memory uses the abbreviations that have worked for years.
