### ISSUE TITLE
"cat: .git/patches/<branch name>/unapplied: No such file or directory" when doing auto-complete for "stg refresh -p"

### ISSUE THREAD

**Issue by andre-qumulo** [stacked-git/stgit#291]
I have a branch that isn't my main branch on my repo.  Let's say it's name my_changes.  I created this by being on main, running `stg init` and then `stg branch --create my_changes`

I have several patches that are all applied
some_patch
another_patch
yet_another_patch

I have several changes that I want in another_patch.

I type `stg refresh -p another_` and then tab for auto-completion.  

My terminal hangs with the output:
```
stg refresh -p code_cat: .git/patches/my_changes/unapplied: No such file or directory
cat: .git/patches/my_changes/applied: No such file or directory
```

I get the same error if I pop down to another_patch.

I am on STG 2.2.0 and Git 2.39.2.

Any suggestions on what to configure to get it working?

**Comment by jpgrayson** [comment]
What shell are you using?

This looks like an old completion script. StGit used to keep stack/patch state/metadata in files found in `.git/patches/<branchname>`, but that state is now kept as git objects within the repository under the `refs/stacks/<branchname>` reference. So when the shell completion tries `cat .git/patches/my_changes/unapplied`, it is not going to find anything because StGit doesn't keep stack metadata there since before StGit 1.0.

StGit ships with completion support for bash, fish, and zsh. Ideally these completion scripts would be packaged by your distribution and placed in the right locations at install-time ([the Arch package](https://aur.archlinux.org/packages/stgit) that I maintain does this), but I know that most distributions ship very, very out of date StGit packages. (https://repology.org/project/stgit/versions).

So I suspect that you either have an old completion script from an old, distro-provided version of StGit; or you're using zsh which ships with an old/broken completion StGit script. N.B. I have contributed a change to zsh that removes these broken completions since StGit ships its own working/complete zsh completions. This change should appear in the next zsh release (along with a repairs/improvements to zsh's vcs_info support for StGit).

If you are installing StGit through a channel that doesn't deal with installing StGit's shell completions (e.g. a plain `cargo install` will only install the `stg` executable, but not any of the completion scripts, man pages, etc.), you can run `stg completion bash`, `stg completion fish`, or `stg completion zsh` to get the completion script for those shells. There are brief instructions at the tops of these scripts that describe how/where to use the script.

**Comment by andre-qumulo** [comment]
Ah, I am using Ubuntu so I think I installed from apt/snap the first time but then I was installed StGit from tar and I think I didn't run `make install install-completion`.

I ran `make install install-completion`, refreshed my terminal, and now it seems to be working.

**Comment by jpgrayson** [comment]
Great! I'm glad it's now working for you. Thanks for following-up on the issue too.
