### ISSUE TITLE
stg does not work in worktree

### ISSUE THREAD

**Issue by larsks** [stacked-git/stgit#297]
In order to start refactoring a bunch of commits I cloned an existing stg patch series to a new branch:

```
stg branch --clone devel-v2
```

But I wanted the original series check out for reference purposes, so I tried:

```
git worktree add ../devel-v1 devel-v1
```

Unfortunately, when in the worktree, `stg` is unable to see the patch series:

```
$ cd ../devel-v1
$ stg series | wc -l
0
```

But from the main working directory, this works:

```
$ stg series -b devel-v1 | wc -l
25
```

---

To be clear, the commits are checked out in the worktree, so I have the content I want; I just can't navigate it using `stg` commands.

**Comment by snits** [comment]
I am running into issues with this as well.

```
$  stg --version
Stacked Git 2.2.0 (02ba5a5c0)
Copyright (C) 2005-2022 StGit authors
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
SPDX-License-Identifier: GPL-2.0-only
git version 2.38.1
```

I was seeing it with 2.2.0 as well. Prior to a recent build of 2.2.0, and 02ba5a5c0 today I'm not sure what previous version that I was using.

In addition to what @larsks mentions, I have stg branches that were originally created while in the worktree directory that ended up in a state where they couldn't find their metadata, with stg series returning can't find object error. There was a recent git gc done, so that possibly contributed to the problem there. The applied patches were there, and luckily I had everything applied at that point, so I was able to do a new stg init, and uncommit the commits back into stg.

last commit before the gitoxide switch works: 8a3a82b21a31 ("refactor: patchedit imports")
commit 054edb2c44d6 ("refactor: Use gitoxide instead of git2") had a build error from git-glob and that persisted up to around 543988989f29 ("fix: enable local-time in commits.") so I couldn't narrow it down further to see if it started appearing someplace later than the switch to gitoxide, though that seems like it would probably be a likely candidate for where it started to not work.

**Comment by larsks** [comment]
It also looks as if stgit is unable to find hook scripts when in a worktree (in addition to the problems with hook scripts noted in #295).

**Comment by jpgrayson** [comment]
I appreciate this issue report, @larsks. And the additional color, @snits. There were definitely some major problems with running StGit from a linked worktree.

The first and most major issue was a problem upstream in gitoxide that caused StGit's stack and patch refs to be created as per-worktree instead of shared. That issue was resolved with [this PR](https://github.com/Byron/gitoxide/pull/794).

With that fixed, I found that config, templates, and hooks were being looked for in per-worktree paths instead of the repo common path.

Lastly, there was an issue with shell aliases not working correctly due to StGit trying to hard to set the `GIT_DIR` environment variable.

I added several new scripts to the test suite that exercise StGit running from a linked worktree.

With all this resolved, I'm feeling pretty confident that StGit works with linked worktrees (again). Please open new issues if you see any more problems with running in linked worktrees.

**Comment by larsks** [comment]
Thanks for the fix! I really appreciate your work on this project.
