### ISSUE TITLE
Permanently disable logging

### ISSUE THREAD

**Issue by TerraTech** [stacked-git/stgit#32]
stgit-0.19

Is there a way to disable logging, either by an environment variable or a config option?  I looked through the source and couldn't find anything relevant.

I'd like to disable either by global or by repo.  If disabled globally, then one could override and enable by repo.

The reason I'd like to disable is it can clutter up the commit tree as I use the following quite a bit:
```sh
$ git log --graph --pretty=oneline --abbrev-commit --decorate --all --date-order
and
$ git log --abbrev-commit --all --boundary --branches --date-order --decorate --graph --oneline --pretty=oneline --simplify-by-decoration --topo-order
```
FWIW - I am aware of: ```stg log --clear```

Thank you.

**Comment by jpgrayson** [comment]
Hi @TerraTech. The short answer is no, there is currently no option to disable logging in stgit.

The log is essential for stgit's rollback features: `stg undo`, `stg redo`, and `stg reset`. I think the assumption stgit makes is that the benefits of those features outweigh the noise that can emerge in some `git log` commands.

I suppose it could be reasonable for some users to forego the log and give up those features. However, I believe most stgit users are better off, in net, with the log enabled. I would personally be hesitant to add the complexity of a log disable switch.

For the `git log` commands shown, I was able to use `--exclude` to get it to show what I think you are interested in:

`git log --graph --pretty=oneline --abbrev-commit --decorate --exclude='*.stgit' --exclude='refs/patches/*' --all --date-order`

There is more going on in the second command, so after a few tries I was unable to tame it, but I still suspect it may be possible. So I guess my hope is that instead of disabling stgit's log, alternative `git log` command lines can be crafted to serve your use cases.

**Comment by TerraTech** [comment]
I would be ok with giving up those three features.  The 'disable logging' switch or envariable would be an opt-in endeavor and appropriate 'warning' in the docs would state as such.

Like you, I could use '--exclude' in the first case, but even Thor's hammer could not get the 2nd one to cooperate due to how ```--all``` works.

FYI, I use the 2nd one heavily and have both aliased respectively:
1. git brg
2. git brga  (I use this 95% of the time over the former countless times in a day's work)

As a bonus, I'll add a couple other useful aliases that I depend on.
```sh
$ git brgs
brgs = log --abbrev-commit --boundary --branches --date-order --decorate --graph --oneline --pretty=oneline --simplify-by-decoration --topo-order
$ git brgsa
brgsa = log --abbrev-commit --all --boundary --branches --date-order --decorate --graph --oneline --pretty=oneline --simplify-by-decoration --topo-order
```
It gives me a birds eye view of how my various branches interrelate.

I would like to advocate for adding the switch/envariable and allow those that want it to opt-in to disable logging.  Perhaps adding a 'git config' local item would work as well to make it repo specific.

Thank you.

**Comment by jpgrayson** [comment]
The complexity that concerns me with this proposal is not so much user-facing complexity (although certainly every configuration knob adds some incremental complexity for the user), it is more about the complexity to the stgit code itself. This project does not have a lot of development bandwidth--its mostly just me contributing at this point--so I'm hesitant to add any new features that may add material ongoing complexity to the stgit code base.

However, if you (@TerraTech) (or anyone else) want to do the leg work to write this feature (and tests!), I would be willing to help shepherd the PR to a mergable state.

>  Perhaps adding a 'git config' local item would work as well to make it repo specific.

Yes, if this feature were to be added, controlling it with a config item seems like a good approach.

**Comment by jpgrayson** [comment]
Just committed 7641796 which moves the stack metadata/log from `refs/heads/<branch>.stgit` to `refs/stacks/<branch>`. Because the stack log is no longer in the branches namespace (i.e. no longer in `refs/heads`), the output of `git log --branches` is no longer cluttered with all the stack log action.

And for applications of `git log` with the `--all` option, `--exclude=refs/stacks/*` can be used to exclude stack log commits. E.g.:

```sh
git log --exclude='refs/stacks/*' --all \
        --abbrev-commit --boundary \
        --date-order --decorate --graph --oneline \
        --pretty=oneline --simplify-by-decoration \
        --topo-order
```

N.B. `--exclude` must precede `--all`. See git-log(1).

I'm going to close this issue because the log clutter is mitigated as well as I know how and I'm not going to support totally disabling the StGit log.
