### ISSUE TITLE
RFE: allow --3way mode for `stg import`

### ISSUE THREAD

**Issue by jnsnow** [stacked-git/stgit#36]
--reject is nice, but I often like to try --3way first.

(Use case is using stg to load patchsets from QEMU mailing list as a stack for review purposes. Sometimes the patches are slightly out of date and --3way or --reject is needed to get the patches loaded.)

I could likely write a patch to just "plumb" a --3way option through, but I was wondering if a more general purpose solution for passing "arbitrary" arguments to `git apply` would be wanted instead, or if "the stupid approach" here was actually best. It might also be nice, because mbox files can have multiple patches within them, to allow the --interactive mode, too.

Please advise!
--js

**Comment by jpgrayson** [comment]
The case for `--3way` makes sense to me.

Regarding passing arbitrary options to `git apply`, I personally do not prefer that approach. Stgit has this kind of arbitrary option pass-through with `--diff-opts` on several subcommands (`diff`, `show`, `edit`, ...).

One of the problems is CLI discoverability. Stgit's help does not present the user with all the valid/useful diff options. This could be solved with more documentation.

Another problem is that it becomes unclear/opaque as to how user-selected diff options interact with stgit's default diff options. I.e. how does the user know which ones stgit already applies? Or what the behavior will be when a user-provided option conflicts with a stgit default option?

Lastly, it makes the stgit code more complex because in order to have reasonable behaviors when a user-provided option conflicts with stgit's default option set, stgit has to first parse the user's pass-through options and then resolve the conflict somehow. At this point, we are already baking-in knowledge about `git`'s options, so why not explicitly enumerate the useful options as part of stgit's interface?

Anyway, I would be open to a patch to add the `--3way` option to `stg import`, along with potentially other options that map to useful `git apply` modes/options, but I'd need to be sold on the general-purpose pass-through.

**Comment by wberrier** [comment]
Another option that I'd be interested in from `git-apply` is `--directory`.

The repository I'm importing to doesn't have the same base path as the repository I'm importing from.  I'm ok that the generated patches would have different paths.  Having this option would help bootstrap the process using `stgit` instead of manually using `git am` and `git apply`.

**Comment by lkraav** [comment]
Trying to backport https://patchwork.kernel.org/project/linux-pci/cover/20220301041943.2935892-1-david.e.box@linux.intel.com/ on older kernel, I was reminded `stg import --3way` sure would be nice.
