### ISSUE TITLE
"stg mail" still sends lines terminated with <LF>-only

### ISSUE THREAD

**Issue by chucklever** [stacked-git/stgit#403]
```
[cel@klimt odd-releases]$ stg mail -a -e -vv5 --to=jeff --to=amir --cc=trond --cc=fsdevel --cc=nfs --cc=viro --cc=christian
Checking the validity of the patches ... done
Invoking the editor: "/usr/bin/vim .stgitmail.txt" ... done
Sending the cover message ... 
  stg mail: (521, b'5.5.2 smtp.kernel.org Error: bare <LF> received')
[cel@klimt odd-releases]$
```

Kees Cook explains:
> SMTP servers until recently would accept non-conforming traffic (i.e.
> only \<LF\> line-endings instead of \<CR\>\<LR\> line-endings), but this led
> to a security flaw:
> https://sec-consult.com/blog/detail/smtp-smuggling-spoofing-e-mails-worldwide/
> 
> So AIUI, your MTA will need to be adjusted to send \<CR\>\<LF\> lines.

Note however:

```
[cel@klimt odd-releases]$ stg version
Stacked Git 1.5
git version 2.43.0
Python 3.11.7
[cel@klimt odd-releases]$ cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)
```

stgit 1.5 appears to be the latest available version in any distribution. OpenSuSE Leap still has 0.17 !!

So, for versions earlier than 2.0, I'm hoping there is a configuration setting that will address this, if you happen to know of one. For versions after 2.0, you can, of course, make a code change to address this (if it's not already fixed there).

**Comment by jpgrayson** [comment]
> stgit 1.5 appears to be the latest available version in any distribution.

Gentoo, Arch, GUIX, nix, homebrew, and some other less well known distros are packaging StGit 2.x.

> OpenSuSE Leap still has 0.17 !!

Looks like openSUSE _just_ [got StGit 2.4.2](https://build.opensuse.org/package/show/openSUSE:Factory/stgit) into the pipeline a day ago.

But, point taken, it's somewhat frustrating for me that both the Debian/Ubuntu and Fedora/RedHat world are stuck on extremely outdated versions of StGit.

That's why I'm now publishing universal, statically-linked rpm and deb packages [with StGit releases](https://github.com/stacked-git/stgit/releases/tag/v2.4.2). Also msi packages for Windows.

Regarding this issue specifically, in StGit 2.x the `stg mail` command is replaced with `stg email format` and `stg email send` commands that act as thin wrappers on `git format-patch` and `git send-email`, respectively. So unless `git send-email` is exposed to this problem, it won't be an issue with StGit 2.x.

Note that in StGit 1.x (and 0.x), the Python stdlib `email` and `smtplib` modules were used to compose and send emails; so a very different strategy. There is the `stg mail --git` option which causes the email to be sent using `git send-email`. Perhaps that would smooth-over this line endings issue?

**Comment by chucklever** [comment]
> Note that in StGit 1.x (and 0.x), the Python stdlib `email` and `smtplib` modules were used to compose and send emails; so a very different strategy. There is the `stg mail --git` option which causes the email to be sent using `git send-email`. Perhaps that would smooth-over this line endings issue?

The `git send-email` support in StGit 1.x has its own issues, unfortunately (eg, email aliases don't work quite the same way). For now, my SMTP relayer has disabled rejecting email from LF-only MUAs, if the MUA authenticates.
