### ISSUE TITLE
"new, pop, edit, refresh, push" results in empty top patch?

### ISSUE THREAD

**Issue by kqr** [stacked-git/stgit#446]
I might be misunderstanding something about how stg operates here, but here's something I often find myself doing, once I've accumulated a little too much work in the topmost patch.

1. I create a new patch. This patch – I imagine – is going to preserve all my work so far.
2. I pop this new patch. The work tree is still identical, since both the top two patches contain the same revision of the work.
3. I now remove some of my previous work from the work tree.
4. I refresh the current patch (which is at this point the penultimate in the series)
5. I push the ultimate patch, which I thought would contain the complete set of work.

At this point, I would expect to sort out some conflicts between the penultimate and ultimate patch, but what happens is the ultimate patch is empty! Which means I "lost" my work, the work I thought was preserved in the popped patch while I was working on underlying patches.

What am I misunderstanding about the stg model?

**Comment by jpgrayson** [comment]
At step 1, when creating a new patch, the working tree still contains all the changes affected by all previous patches, but the new patch itself is empty. Perhaps the key thing here is that a "patch" in StGit is a diff; i.e. it captures the diff between two states of the repository's tree. So by saying that the new patch is "empty", that means that it does not capture any differences to the tree.

At step 2, once you've popped that newly created patch, you are sort of right insofar as your working tree will be in the same state when either the original patch A is applied or both A and the new patch B is applied. But the patches themselves *are not* the same. Patch A is non-empty (it captures diffs) whereas B is empty.

In steps 3 and 4, when you modify the working tree and refresh patch A, the diffs captured by patch A are now different.

But patch B is still empty, so in step 5, you are pushing an empty patch which results in the same tree as with just A applied.

All that said, there actually exists an advanced option that can be used to make this workflow do what you want. StGit remembers patches by recording the commit hash and parent commit hash. And since a commit points to a git tree object, this is isomorphic with a StGit patch being recorded as a tree and a parent tree.

Point being: `stg push --set-tree` can be used to push a patch, but instead of the working tree being updated based on patch application, the working tree is updated to the patch's recorded tree.

So your step 5 would give you exactly what you wanted if you did `stg push --set-tree`.

**Comment by kqr** [comment]
Oh, okay! So after step 4,

- Patch B is secretly a reference to commit B
- Commit B references the same tree as commit A
- And this tells StGit that "patch B is empty".

While

- Patch A used to secretly reference commit A
- But after refreshing, patch A now references commit A'
- The contents of patch A as far as StGit is concerned is now whatever the diff is between A' and the parent commit of patch A?

But, critically for my purposes, since patch B still has commit A as a parent – rather than commit A' – StGit sees patch B as empty and thus applies an empty patch.

----

After step 5 – when I do a normal `stg push` without `--set-tree`, will patch B now secretly reference a commit B' which references the same tree as A'?

**Comment by kqr** [comment]
What I'm conceptually trying to do is "take this tree and create an intermediary state with some of the changes applied". From my current understanding of StGit this might be difficult since it requires simultaneously creating two patches or diffs: one from A to intermediary state B, but also one from intermediary state B that preserves the final state C.

But! Either `stg push --set-tree` is the thing that lets me do this, or there's some other way of wielding StGit that I'm missing out on. Willing to learn!
