### ISSUE TITLE
Argv ordering requirements unnecessarily strict

### ISSUE THREAD

**Issue by mandolaerik** [stacked-git/stgit#448]
With Python-based stgit, you could add flags to the end of argv, e.g. the following would work:
```
$ stg float foo
error: worktree not clean; use `refresh` or `reset --hard`
$ stg float foo -k
$
```
With stg 2.4.6, I get this instead:
```
$ stg float foo -k
error: patch `-k` does not exist
```
... and I need to reorder my argv to the following, which I find less ergonomic:v
```
$ stg float -k foo
```
Is this change intentional? If I have a patch named `-k`, then (a) I don't deserve nice treatment, and (b) I will still only be able to float that patch if I float another patch at the same time.

**Comment by jpgrayson** [comment]
Thank you for posting this issue report, @mandolaerik.

> Is this change intentional?

Yes, but because it was needed to enable the new patch locator syntax introduced in StGit 2.2. This feature enables patches to be specified by location in addition to by name. For example, a patch can now be specified by relative offset, e.g. `stg push +3' or `stg pop -3`. Before StGit 2.2, patches could only be specified by name.

In order to support all the new patch locator forms, the command line parsing was changed such that regular command line options must precede patch location and/or patch range arguments. This was a compromise.

> If I have a patch named -k, then (a) I don't deserve nice treatment

I don't recommend naming patches with a leading dash, but...

> (b) I will still only be able to float that patch if I float another patch at the same time.

you would be treated fairly because you could use `stg float -- -k` to float your patch named `-k`. Or `stg float -k -- -k` if you also wanted the keep option.

I know this new behavior is different and less ergonomic for this particular use case. I'm sorry about that. But the patch location capabilities improve ergonomics in a bunch of other contexts and so are here to stay.

**Comment by mandolaerik** [comment]
> a patch can now be specified by relative offset, e.g. stg push +3' or stg pop -3`

Oh, I did not know about that, will definitely use.

However, I don't understand why this would conflicts with `-k`: Couldn't we distinguish flags from patch IDs by some simple context-free grammar, like `[-][^0-9].*`?

**Comment by jpgrayson** [comment]
I don't know that we can do that while still getting s as much leverage from clap.

I also think there is a case to be made for the consistency of requiring options to come before patch arguments versus having them sometimes work, but other times not (e.g. when a patch has the same name as an option).

**Comment by mandolaerik** [comment]
> I also think there is a case to be made for the consistency of requiring options to come before patch arguments versus having them sometimes work, but other times not (e.g. when a patch has the same name as an option).

Can't we define that
* if `--` is present, then all options come before that, and positionals after
* if `--` is not present, then everything that starts with `-` is interpreted as an option (except of course for unary args to options, like `-x` in `sink -t -x`)
This way, there is a clear rule, no "sometimes it works, sometimes not".

Would this make sense to you in principle? If so, once I have accumulated enough annoyance I can maybe use this as an excuse to learn a bit of rust and see if this can be done with clap.

**Comment by jpgrayson** [comment]
> if -- is not present, then everything that starts with - is interpreted as an option (except of course for unary args to options, like -x in sink -t -x)
This way, there is a clear rule, no "sometimes it works, sometimes not".

> Would this make sense to you in principle?

It does make sense. But I chose the current behavior to enable ergonomic use of relative patch indices. E.g. `stg float -2` versus having to write `stg float -- -2`.

There are a bunch of tradeoffs w.r.t. command line parsing of patch locations, paths, and how those fit together with command line options. I'm reasonably happy with the current set of tradeoffs.

> If so, once I have accumulated enough annoyance I can maybe use this as an excuse to learn a bit of rust and see if this can be done with clap.

I'm open to improvements, but please consider consistency across StGit commands and whether a change may break a current workflow.

Thanks for digging into this.
