### ISSUE TITLE
`stg` workflow with commit hooks?

### ISSUE THREAD

**Issue by lkraav** [stacked-git/stgit#45]
Packages like https://github.com/typicode/husky are making git hooks ~~great again~~ easy.

Example husky pre-commit hooks setup: https://github.com/web-padawan/aybolit/blob/master/package.json#L75

Example `package.json "lint-staged"` key: https://github.com/web-padawan/aybolit/blob/master/package.json#L80

I'm noticing neither `stg refresh` or  `stg commit` trigger these (at least?) pre-commit hooks. This creates risks of offroading commit quality and causes future PR difficulties, because `stg` users commits aren't being auto-corrected by `prettier --fix`, but native `git` users commits are. Their PRs now often also include involuntary corrections of previous `stg` commits, or require special attention to exclude hunks.

Any thoughts towards what a solution could be? Am I missing something simple about how I should configure `stgit` to work with commit hooks?

**Comment by jpgrayson** [comment]
Currently stgit only runs the `commit-msg` hook. It is run for `refresh`, `edit`, `squash`, and `new` commands.

It seems quite reasonable for stgit to also support the `pre-commit` hook. Also the `prepare-commit-msg` hook might also make sense.

Other hooks are less clear to me. Some may already be supported implicitly by way of stgit running git commands that execute hooks. This would need to be audited.

**Comment by lkraav** [comment]
What would it take to get `pre-commit` hook in?

**Comment by lkraav** [comment]
Poked around some, I would think we would add something like `def run_pre_commit_hook()` somewhere around https://github.com/stacked-git/stgit/blob/v0.22/stgit/commands/common.py#L447

**Comment by jpgrayson** [comment]
Yes, code for running the `pre-commit` hook is one thing that is needed. That part should be pretty straightforward since the `pre-commit` hook semantics are straightforward: no parameters and a simple pass/fail outcome.

My initial thought was that potentially many `stg` sub-commands would have to comprehend and integrate with the `pre-commit` hook, but now I actually wonder if it might be sufficient for `pre-commit` to only be executed by `stg refresh`?

The rationale would be that git only executes `pre-commit` for `git commit` and `stg refresh` is most like `git commit` in that it is StGit's high-level (porcelain) command for modifying the contents of a patch.  So for `stg` to be like `git`, we would **not** run `pre-commit` for subcommands like `pull`, `rebase`, `pick`, and `squash`, just as Git does not run `pre-commit`, for example, for its `pull`, `rebase`, `cherry-pick`, or `merge` commands.

Only integrating `pre-commit` with `refresh` would greatly limit the scope of this feature. I'm interested in other's opinions about whether limiting this to `refresh` is actually okay/correct?

Lastly, the first step should be writing test cases that exercise `pre-commit`.

**Comment by lkraav** [comment]
> Only integrating pre-commit with refresh would greatly limit the scope of this feature. I'm interested in other's opinions about whether limiting this to refresh is actually okay/correct?

Yes, `refresh` is That One Thing for sure.

**Comment by lkraav** [comment]
Since I bandwidth issues, I posted an Upwork job at https://www.upwork.com/jobs/~01c2ade1c313fd502d to see if I can find someone to move this along faster.
