### ISSUE TITLE
SSL detection broken in mail command

### ISSUE THREAD

**Issue by ahduyck** [stacked-git/stgit#57]
When trying to use the mail command on Fedora 31 w/ Python 3.7 it appears that the command will always fail with the message:
  stg mail: cannot use TLS - no SSL support in Python

In digging into this I found the line generating it was:
               if not hasattr(socket, 'ssl'):
                    raise CmdException("cannot use TLS - no SSL support in Python")

A bit of further digging seems to show that hasattr(socket, 'ssl') is not a valid away to test for if there is ssl support or not as socket.ssl was deprecated [1].

It appears the correct way to do this is to do an import in a try/except block as seen in this bugzilla [2], but I am not familiar enough with Python to be certain if this is the correct approach.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1553834
[2]: https://github.com/zopefoundation/zope.sendmail/issues/9

**Comment by jpgrayson** [comment]
Thank you for reporting this issue and for the helpful reference links, @ahduyck. Much appreciated!

I have pushed a repair for this issue. The approach I took was to unconditionally call `starttls()` and handle the possible exceptions instead of proactively testing for SSL support in the Python interpreter. The `smtplib.SMTP.starttls()` method already does its own check for SSL support and will raise `RuntimeError` if it is not present.

Anyway, there are a lot of blind spots in StGit's test suite w.r.t. `stg mail`. It would be much appreciated if you could try out this repair in the Fedora 31 / Python 3.7 environment where the issue was first spotted.

**Comment by ahduyck** [comment]
That seems to work for me. Thanks.
