### ISSUE TITLE
Feature request: Add option to stg squash to preserve text below the `---` line

### ISSUE THREAD

**Issue by neuschaefer** [stacked-git/stgit#71]
When using `stg squash` and editing the patch description, I'd like `stg squash` to preserve the text below the `---` line, because I keep a list of changes between the patch's published revisions there.
Currently I need to replace `---` with something else before I finish editing in `stg squash` and later change it back with `stg edit`, but it would be more convenient if I could pass an option to `stg squash` that would cause it to perserve the text.

**Comment by jpgrayson** [comment]
Hi @neuschaefer. Sorry for the extremely delayed reply. I'm thinking about how squash's behavior could be changed or improved to help with this use case.

I'm wondering whether it might help if StGit adopted strategy similar to `git rebase -i` w.r.t. the message presented when squashing. For example, here is what is presented by `stg squash -n squashed -- p0 p1 p2`:

```
foo 0


---
Everything following the line with "---" will be ignored

p1--------------------------------------------------------------------

foo 1


p2--------------------------------------------------------------------

foo 2
```

Whereas this is what is presented by `git rebase -i` when picking p0 and squashing p1 and p2:

```
# This is a combination of 3 commits.
# This is the 1st commit message:

foo 1

# This is the commit message #2:

foo 2

# This is the commit message #3:

foo 3

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    A Ú Thor <author@example.com>
# Date:      Fri Jun 18 19:02:25 2021 +0000
#
# interactive rebase in progress; onto 2c3baa8
# Last commands done (3 commands done):
#    squash 0f8681c foo 2
#    squash 893b6f1 foo 3
# No commands remaining.
# You are currently rebasing branch 'master' on '2c3baa8'.
#
# Changes to be committed:
#	modified:   foo.txt
#
# Untracked files:
#	.local/
#
```

What I'm suggesting is that StGit could use leading `#` as discardable comments instead of using `---` to separate the viable message at the top from the discardable material below.

It seems like this approach would solve the immediate problem of `---` having a different meaning in your messages.

It also seems like this approach might StGit more familiar to those coming from vanilla git. I also think I personally might prefer to edit squash messages structured this way.

Thoughts?

**Comment by neuschaefer** [comment]
Hello @jpgrayson.

Assuming that in your proposal, any --- line in a commit message will be ignored and preserved, rather than cut off, I think it would be fine for my use case.

I imagine that my use case is somewhat rare, and I don't need the default behavior of `stg squash` to change. If a solution involves an option that I would have to set in my git config in order to preserve the --- line, I'd be ok with that, too.

To elaborate my use case some more: I specifically want to be able to keep the last --- line and the text below it, because I send out patches by email, that use this section for semantically important information (the changelog between patch revisions, and sometimes other information). This is information that I want to maintain as part of the commit message and send out as part of the patch email, but due to the --- line it will be dropped once it is applied to git by the receiver.
