### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by jorgk3** [stacked-git/stgit#95]
From https://github.com/stacked-git/stgit/issues/78 I derive that this should be working on Windows. So I did this:

Installed Python 3.9.1, that goes into C:\Users\jorgk\AppData\Local\Programs\Python\Python39.

git clone https://github.com/stacked-git/stgit.git
cd stgit
make prefix=P:\src\stgit-installed install
That worked.
(install-doc doesn't work due to make63323.sh: line 1: asciidoc: command not found).

Then went to the directory housing the project I want to work on:
stg init
That gives: 'stg' is not recognized as an internal or external command, operable program or batch file.
No surprise.

Next I renamed P:\src\stgit-installed\Scripts\stg to P:\src\stgit-installed\Scripts\stg.py

Next try:
P:\src\stgit-installed\Scripts\stg.py init
Traceback (most recent call last):
  File "P:\src\stgit-installed\Scripts\stg.py", line 39, in <module>
    from stgit.main import main
ModuleNotFoundError: No module named 'stgit'

I'm sorry if this is a really silly issue, but I can't see any documentation for Windows.

**Comment by jpgrayson** [comment]
Hi @jorgk3. Sorry that StGit isn't easy to get working on Windows.

I suspect that most people that use StGit on Windows either use Cygwin or WSL. That said, it seems like you're pretty close to having it running in a native Windows environment.

Seems like the next piece of the puzzle is ensuring that the StGit installation is in your `PYTHONPATH` environment variable. This section from the Python docs shows a relevant example:

https://docs.python.org/3/using/windows.html#excursus-setting-environment-variables

Another possible hurdle is that the Git executable (`git.exe`) needs to be in your `PATH` environment variable. StGit calls Git to do almost all of its work.

It might be helpful to write a batch wrapper (e.g. `stg.bat`) that exists in your `PATH`, sets-up `PYTHONPATH` to include your StGit installation location, maybe sets-up `PATH` to point at your Git executable, and then invokes the main `stg` Python script.

**Comment by jorgk3** [comment]
Thanks for the comment. "your StGit installation location" - so what is that exactly? I set up stg.bat as suggested with:
```
set PYTHONPATH=%PYTHONPATH%;P:\src\stgit-installed\Lib\site-packages\
P:\src\stgit-installed\Scripts\stg.py
```
and that gets me further running into the next error. To be continued.

**Comment by jorgk3** [comment]
OK, with these two scripts placed into the path, I got it going:
vi.bat (since stg seems to want to run vi, maybe that's configurable somewhere)
```
C:\Program Files\Notepad++\notepad++.exe" %*
```
stg.bat (after renaming Scripts\stg to Scripts\stg.py):
```
@set PYTHONPATH=%PYTHONPATH%;P:\src\stgit-installed\Lib\site-packages\
@P:\src\stgit-installed\Scripts\stg.py %*
```
I did an init, new, refresh, pop, and now the repo looks like this when viewed in "Git Extensions":
![image](https://user-images.githubusercontent.com/8466558/107149263-ed587280-6957-11eb-88a8-bb9d910d7625.png)
So I guess all the stg action happens on the master.stgit branch and I don't have to worry about it. And it gets more with every push/pop/etc.
After a `git branch -D master.stgit` it still looks like:
![image](https://user-images.githubusercontent.com/8466558/107149399-a9b23880-6958-11eb-85d5-ad8cc8d5036d.png)
But that's not related to Windows support.

**Comment by jpgrayson** [comment]
> since stg seems to want to run vi, maybe that's configurable somewhere

Several StGit commands (`refresh`, `edit`, ...) will invoke your editor of choice to edit commit messages. The editor that is executed is configurable by a variety of sources. From `stgit/utils.py`:

```python
def get_editor():
    for editor in [
        environ_get('GIT_EDITOR'),
        config.get('stgit.editor'),  # legacy
        config.get('core.editor'),
        environ_get('VISUAL'),
        environ_get('EDITOR'),
        'vi',
    ]:
        if editor:
            return editor
```

Insofar as you were seeing StGit invoke `vi`, that means that none of the preceding environment variables or Git config items were set. Your best bet would be to set `core.editor` in you global Git configuration, since that will be useful when using `git` from the command line too.

---

> repo looks like this when viewed in "Git Extensions" [...] I guess all the stg action happens on the master.stgit branch and I don't have to worry about it.

StGit keeps stack metadata in the `<branch>.stgit` branches. That metadata branch is updated when the various StGit commands modify stack state. And because of <reasons>, the commits in the metadata branch identify commits in the corresponding branch (i.e. *master*) as parents. This is what leads to the wild DAG drawn by Git Extensions.

I've not used Git Extensions, but with `gitk` it is possible and useful to configure it to not show the `.stgit` branches. This leaves your regular branch DAG cleaner looking in such tools.

---

> After a `git branch -D master.stgit` it still looks like: [...]

Deleting the StGit metadata branch manually will leave the per-patch refs in the repo; e.g. `refs/patches/master/patch`. The nominal way to remove all the StGit state associated with a branch, including patch refs, is with the `stg branch --cleanup` command.

---

I'm going to close-out this issue. If there are any actionable changes that would help StGit work better on Windows, new issues can be opened.

**Comment by jorgk3** [comment]
Thanks for your help. I've just done my first commit using StGit. I think it will be a very useful tool. `stg branch --cleanup` worked like a charm.
